# Generated by Django 4.2.13 on 2025-02-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_auto_20250227_0935"),
    ]

    operations = [
        migrations.DeleteModel(name="CategoryMain",),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
