# Generated by Django 4.2.13 on 2025-02-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_variation"),
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="varitations",
            field=models.ManyToManyField(blank=True, to="store.variation"),
        ),
    ]
