# Generated by Django 4.2.13 on 2025-02-28 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0002_cartitem_varitations"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem", old_name="varitations", new_name="variations",
        ),
    ]
